name: KiCad CI (AppImage + KiCad 9)

on:
  push:
    paths:
      - 'hw/**'
  pull_request:
    paths:
      - 'hw/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download KiCad 9 AppImage
        run: |
          wget https://downloads.kicad.org/kicad-9.0.3/kicad-9.0.3-x86_64.AppImage -O kicad.AppImage
          chmod +x kicad.AppImage

      - name: Extract AppImage
        run: |
          ./kicad.AppImage --appimage-extract
          export PATH=$PWD/squashfs-root/usr/bin:$PATH

      - name: Install KiBot
        run: |
          python3 -m ensurepip --upgrade
          python3 -m pip install --upgrade pip
          python3 -m pip install kibot==1.8.4

      - name: Run KiBot
        run: |
          kibot -b hw/jtag_switch.kicad_pcb -c hw/.kibot.yaml

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hw-build
          path: |
            hw/docs
            hw/fabrication
